# Generated by Django 3.1 on 2022-03-05 09:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DumpArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=50)),
                ('dimension', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Garbage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garbage_type', models.CharField(max_length=50)),
                ('cost_per_unit', models.CharField(max_length=50)),
                ('garbage_quantity', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('Ravi Zone', 'Ravi Zone'), ('Data Ganj Bukhsh Zone', 'Data Ganj Bukhsh Zone'), ('Shalamar Zone', 'Shalamar Zone'), ('Aziz Bhatti Zone', 'Aziz Bhatti Zone'), ('Samanabad Zone', 'Samanabad Zone'), ('Gulberg Zone', 'Gulberg Zone'), ('Wahga Zone', 'Wahga Zone'), ('Allama Iqbal Zone', 'Allama Iqbal Zone'), ('Nishtar Zone', 'Nishtar Zone')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=150)),
                ('size', models.CharField(max_length=20, null=True)),
                ('color', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=150)),
                ('model_no', models.CharField(max_length=50)),
                ('manager_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WMS.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='user', max_length=20)),
                ('email', models.EmailField(max_length=40, null=True)),
                ('phone', models.CharField(default=' ', max_length=15)),
                ('address', models.CharField(max_length=400)),
                ('zone', models.CharField(choices=[('Ravi Zone', 'Ravi Zone'), ('Data Ganj Bukhsh Zone', 'Data Ganj Bukhsh Zone'), ('Shalamar Zone', 'Shalamar Zone'), ('Aziz Bhatti Zone', 'Aziz Bhatti Zone'), ('Samanabad Zone', 'Samanabad Zone'), ('Gulberg Zone', 'Gulberg Zone'), ('Wahga Zone', 'Wahga Zone'), ('Allama Iqbal Zone', 'Allama Iqbal Zone'), ('Nishtar Zone', 'Nishtar Zone')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('RESOLVED', 'RESOLVED')], default='PENDING', max_length=20)),
                ('complaint', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('dumparea_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WMS.dumparea')),
                ('garbage_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WMS.garbage')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
