# Generated by Django 3.1 on 2022-03-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0002_auto_20220301_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='phone',
            field=models.CharField(default=' ', max_length=15),
        ),
    ]
