# Generated by Django 3.1 on 2022-03-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0002_auto_20220306_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='email',
        ),
        migrations.RemoveField(
            model_name='request',
            name='name',
        ),
    ]
