# Generated by Django 3.1 on 2022-03-06 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0005_contact_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
