# Generated by Django 3.1 on 2022-03-07 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0007_auto_20220306_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddVehicle',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WMS.contact')),
            ],
            bases=('WMS.contact',),
        ),
    ]
