# Generated by Django 3.1 on 2022-03-07 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0008_addvehicle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddVehicle',
        ),
    ]
