# Generated by Django 3.1 on 2022-03-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0011_auto_20220307_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Free', 'Free'), ('On_Duty', 'On_duty')], default='Free', max_length=20),
        ),
    ]
