# Generated by Django 3.1 on 2022-03-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0012_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='zone',
            field=models.CharField(choices=[('Ravi Zone', 'Ravi Zone'), ('Data Ganj Bukhsh Zone', 'Data Ganj Bukhsh Zone'), ('Shalamar Zone', 'Shalamar Zone'), ('Aziz Bhatti Zone', 'Aziz Bhatti Zone'), ('Samanabad Zone', 'Samanabad Zone'), ('Gulberg Zone', 'Gulberg Zone'), ('Wahga Zone', 'Wahga Zone'), ('Allama Iqbal Zone', 'Allama Iqbal Zone'), ('Nishtar Zone', 'Nishtar Zone')], default='Ravi Zone', max_length=50),
        ),
    ]
